version: "2"
linters:
  enable:
    - misspell
    - revive
    - unconvert
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - misc
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - misc
      - third_party$
      - builtin$
      - examples$
